[[redirects]]
  from = "/onlyfans"
  to = "https://gethelp.com/about/"
[[redirects]]
  from = "/instagram"
  to = "https://www.instagram.com/realwayson/"
[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/wayson/"
[[redirects]]
  from = "/animelist"
  to = "https://anilist.co/user/wayson/"
[[redirects]]
  from = "/resume"
  to = "https://jaasonw.github.io/files/resume.pdf"