[[redirects]]
  from = "/onlyfans"
  to = "https://gethelp.com/about/"
[[redirects]]
  from = "/instagram"
  to = "https://www.instagram.com/realwayson/"
[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/wayson/"
[[redirects]]
  from = "/animelist"
  to = "https://anilist.co/user/wayson/"
[[redirects]]
  from = "/resume"
  to = "https://jaasonw.github.io/files/resume.pdf"
[[redirects]]
  from = "/github"
  to = "https://github.com/jaasonw"
[[redirects]]
  from = "/discord"
  to = "https://discord.gg/MwqSCKbUG3"
[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/realwayson"
[[redirects]]
  from = "/spotify"
  to = "https://open.spotify.com/user/fi14v4phgvmdiqk3g5t7cwsvz?si=732b32cce59a470f"
[[redirects]]
  from = "/tiktok"
  to = "https://www.tiktok.com/@realwayson"
[[redirects]]
  from = "/donate"
  to = "https://ko-fi.com/wayson"
[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/channel/UCpHV53n_jlKR4gH3spN8alw"
[[redirects]]
  from = "/youtubealt"
  to = "https://www.youtube.com/channel/UC5zqtuav_Mcu5Jqc5BpRhXA"
[[redirects]]
  from = "/acsform"
  to = "https://forms.gle/KNKVFQF3yPkQwN4p9"
[[redirects]]
